---

- name: install redis
  include_tasks: install.yml

- name: configure instances
  include_tasks: configure.yml
  loop: "{{ multiredis_instances }}"
  loop_control:
    loop_var: redis_instance

- name: disable default redis instance
  service:
    name: "{{ multiredis_package_name }}"
    status: stopped
    enabled: false
  when: multiredis_disable_default_instance
